# Lista 1

In [1]:
import numpy as np

### 1. Calcule o determinante e a matriz inversa das matrizes abaixo utilizando o teorema de Laplace.

In [2]:
# Matriz A
A = np.array([2, 3, -1, 4, 8, 1, 9, 3, 0, 2, 1, 8, -2, 3, -1, 7]).reshape(4,4)
A

array([[ 2,  3, -1,  4],
       [ 8,  1,  9,  3],
       [ 0,  2,  1,  8],
       [-2,  3, -1,  7]])

In [3]:
# Matriz B
B = np.array([1, 2, 1, 2, 1, 2, 1, 2, 1]).reshape(3,3)
B

array([[1, 2, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [4]:
# Determinante de A
det_A = np.linalg.det(A)
print('Determinante de A')
print(det_A)
print('-='*50)
# Matriz Inversa
inv_A = np.linalg.inv(A)
print('A-¹')
print(inv_A)

Determinante de A
341.9999999999999
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
A-¹
[[ 0.26315789 -0.04385965  0.24561404 -0.4122807 ]
 [ 0.05263158  0.15789474 -0.68421053  0.68421053]
 [-0.24561404  0.15204678 -0.25146199  0.3625731 ]
 [ 0.01754386 -0.05847953  0.32748538 -0.21637427]]


In [5]:
# Determinante de B
det_B = np.linalg.det(B)
print('Determinante de B')
print(det_B)

Determinante de B
0.0


In [ ]:
# Matriz Inversa
inv_B = np.linalg.inv(B) # Erro: Conjunto solução não existe

### 2. Escreva os sistemas lineares abaixo no formato matricial e utilize o MATLAB® para obter o vetor incognita. Classifica os sistemas.

##### Lembrando: Ax = b

#### Sistema S1

In [6]:
# Matriz s1 (A)
s1 = np.array([-6, 2, 0, 1, 0, 5, 0, -3, -5]).reshape(3,3)
s1

array([[-6,  2,  0],
       [ 1,  0,  5],
       [ 0, -3, -5]])

In [7]:
# Matriz b (b)
b = np.array([1, 3, 20]).reshape(3,1)
b

array([[ 1],
       [ 3],
       [20]])

In [8]:
# Vetor incógnita (x)
x = np.linalg.solve(s1, b)
x

array([[-3.0625],
       [-8.6875],
       [ 1.2125]])

#### Sistema S2

In [9]:
# Matriz s2
s2 = np.array([1, 1, 1, 2, 2, 2, 0, 1, 2]).reshape(3,3)
s2

array([[1, 1, 1],
       [2, 2, 2],
       [0, 1, 2]])

In [10]:
# Matriz b2 (b)
b2 = np.array([10, 20, 1]).reshape(3,1)
b2

array([[10],
       [20],
       [ 1]])

In [ ]:
# Vetor incógnita (x)
x2 = np.linalg.solve(s2, b2)
x2
# Erro: Sistema Impossível, pois todos os determinantes são zero

### 3. Em um ambiente controlado, e possível determinar a distribuição de temperatura de uma superfície sabendo-se a temperatura na sua borda. T1 a T6 serao as respectivas temperaturas nos pontos 1 a 6, e seus valores correspondem a média da temperatura dos seus 4 vértices mais próximos;

In [11]:
# a) 
# Matriz T do sistema encontrado
T = np.array([-4, 1, 0, 1, 0, 0, 1, -4, 1, 0, 1, 0, 0, 1, -4, 0, 0, 1, 1, 0, 0, -4, 1, 0, 0, 1, 0, 1, -4, 1, 0, 0, 1, 0, 1, -4]).reshape(6,6)
T

array([[-4,  1,  0,  1,  0,  0],
       [ 1, -4,  1,  0,  1,  0],
       [ 0,  1, -4,  0,  0,  1],
       [ 1,  0,  0, -4,  1,  0],
       [ 0,  1,  0,  1, -4,  1],
       [ 0,  0,  1,  0,  1, -4]])

In [12]:
# Matriz b
b = np.array([-40, -30, -50, -40, -30, -50]).reshape(6,1)
b

array([[-40],
       [-30],
       [-50],
       [-40],
       [-30],
       [-50]])

In [13]:
# Vetor solução
x = np.linalg.solve(T,b)
x

array([[21.9047619 ],
       [25.71428571],
       [25.23809524],
       [21.9047619 ],
       [25.71428571],
       [25.23809524]])

### 4. Utilize a matriz de dados A.dat e o vetor coluna b.dat obtidas na pagina do Glover et al. (2011).

In [15]:
# Carregando o arquivo A.dat
matrix_A = np.loadtxt('A.dat')
matrix_A

array([[ 1., -2.,  2., -1.,  2.,  1., -2.],
       [ 3.,  1.,  2.,  0., -1.,  2., -3.],
       [ 0.,  2.,  1.,  1.,  1.,  0.,  3.],
       [ 1., -1.,  1., -1.,  1., -1.,  1.],
       [ 3.,  0.,  1.,  1.,  1.,  2.,  0.],
       [-3.,  2., -1.,  0.,  2.,  1.,  3.],
       [-2.,  1.,  2., -1.,  2., -2.,  1.]])

In [17]:
# Carregando o arquivo b.dat
matrix_b = np.loadtxt('b.dat')
matrix_b = matrix_b.reshape(7,1)
matrix_b

array([[-1.],
       [ 5.],
       [19.],
       [ 2.],
       [13.],
       [11.],
       [ 5.]])

In [18]:
# Valores de x (vetor incógnita)
x = np.linalg.solve(matrix_A, matrix_b)
x

array([[1.],
       [2.],
       [3.],
       [2.],
       [1.],
       [2.],
       [3.]])

In [19]:
# Determinante de matrix_A
det_A = np.linalg.det(matrix_A)
det_A

549.0000000000009

In [20]:
# Posto de A
rank_A = np.linalg.matrix_rank(matrix_A)
rank_A

7

### 5. Baixe a matriz A1.dat e b1.dat.

In [32]:
# Carregando arquivo A1.dat
A1 = np.loadtxt('A1.dat')
A1

array([[ 1., -2.,  2., -1.,  2.,  1., -2.],
       [ 3.,  1.,  2.,  0., -1.,  2., -3.],
       [ 0.,  3.,  1.,  0.,  1.,  3.,  0.],
       [ 1., -1.,  1., -1.,  1., -1.,  1.],
       [ 3.,  0.,  1.,  1.,  1.,  2.,  0.],
       [-3.,  2., -1.,  0.,  2.,  1.,  3.],
       [-2.,  1.,  2., -1.,  2., -2.,  1.]])

In [33]:
# Carregando arquivo b1.dat
b1 = np.loadtxt('b1.dat')
b1 = b1.reshape(7,1)
b1

array([[-1.],
       [ 5.],
       [16.],
       [ 2.],
       [13.],
       [11.],
       [ 5.]])

In [34]:
# Determinante de A1
det_A1 = np.linalg.det(A1)
det_A1

0.0

In [35]:
# Posto de A1
rank_A1 = np.linalg.matrix_rank(A1)
rank_A1

6

In [85]:
# Dimensão de A1
np.shape(A1)

(7, 7)

In [29]:
# Valores de x (vetor incógnita)
x = np.linalg.solve(A1,b1)
# Erro: posto e dimensão da matriz são diferentes

LinAlgError: Singular matrix

In [79]:
# Decomposição de valor singular
u, s, v = np.linalg.svd(A1)
print(np.shape(u))
print(np.shape(s))
print(np.shape(v))

(7, 7)
(7,)
(7, 7)


In [80]:
print(s)

[8.00122471e+00 5.81946470e+00 4.81894148e+00 3.09496176e+00
 2.33690910e+00 9.23094968e-01 1.18894305e-16]


In [81]:
# Diagonal de s
S = np.diag(s)
print(np.shape(S))
print(S)

(7, 7)
[[8.00122471e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.81946470e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.81894148e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.09496176e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  2.33690910e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 9.23094968e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.18894305e-16]]


In [82]:
# Matriz x_A1
x_A1 = u @ S @ v
x_A1

array([[ 1.00000000e+00, -2.00000000e+00,  2.00000000e+00,
        -1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
        -2.00000000e+00],
       [ 3.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         2.32752385e-16, -1.00000000e+00,  2.00000000e+00,
        -3.00000000e+00],
       [ 4.34723192e-16,  3.00000000e+00,  1.00000000e+00,
         3.46533118e-16,  1.00000000e+00,  3.00000000e+00,
         9.38137417e-16],
       [ 1.00000000e+00, -1.00000000e+00,  1.00000000e+00,
        -1.00000000e+00,  1.00000000e+00, -1.00000000e+00,
         1.00000000e+00],
       [ 3.00000000e+00,  3.50004951e-15,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         1.49749334e-15],
       [-3.00000000e+00,  2.00000000e+00, -1.00000000e+00,
        -1.78068448e-17,  2.00000000e+00,  1.00000000e+00,
         3.00000000e+00],
       [-2.00000000e+00,  1.00000000e+00,  2.00000000e+00,
        -1.00000000e+00,  2.00000000e+00, -2.00000000e+00,
         1.0000000

In [83]:
# Comparando as matrizes A1 e x_A1
print(np.std(A1), np.std(x_A1), np.std(A1 - x_A1))
print('Os valores de A1 e x_A1 são próximos?', np.isclose(A1, x_A1).all())

1.5787003759847933 1.5787003759847935 1.2784965753809472e-15
Os valores de A1 e x_A1 são próximos? True


In [84]:
# Encontrando os valores de x
x_svd = np.linalg.solve(x_A1,b1)
x_svd

array([[-0.97173391],
       [-0.25341019],
       [ 6.89652178],
       [ 3.19712416],
       [-2.26275016],
       [ 4.04215298],
       [ 5.32382925]])