# Lista 3

**1. O arquivo TraceMeast.mat contém uma lista de medidas de metais traço hipotéticos extraídos de um testemunho de sedimento. Acredita-se que a amostra de sedimentos contém um determinado numero de minerais diferentes. Use a ACP para calcular quantos minerais existem nesta amostra (as componentes principais), a abundancia relativa de cada um deles (os respectivos autovalores) e acomposição de cada componente (a carga fatorial).**

In [1]:
# Importando as bibliotecas
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from scipy.io import loadmat

In [2]:
# Importando e verificando o tipo de dado
data = loadmat('TraceMeast.mat')
print(type(data))

<class 'dict'>


In [3]:
# Identificando o tipo de cada chave no dicionario
for key in data.keys():
    print(key, "\t", type(data[key]))

__header__ 	 <class 'bytes'>
__version__ 	 <class 'str'>
__globals__ 	 <class 'list'>
X 	 <class 'numpy.ndarray'>


In [4]:
# Acessando os dados (chave 'X')
print(data.get('X'))

[[17.32672214  6.73041586  0.36110256  1.19024533  2.83713574 10.17976095]
 [17.76026946 16.94755209  0.60245803  2.82567007  4.35602978 23.58981191]
 [30.35627093 13.24192505  0.38814543  2.16711513  5.71440525 20.90288338]
 ...
 [33.71082849 17.87511205  0.73053152  3.06722471  6.86157373 27.51404659]
 [19.22070831 12.04885047  0.37782179  1.97199417  3.88254551 17.44803857]
 [57.71969283 14.07204571  0.50197082  2.40170666  9.90925922 26.64487764]]


In [5]:
# Associando os dados a variável data
data = data.get('X')

In [6]:
# Dimensões do dado
data.shape

(250, 6)

In [7]:
# PCA
pca = PCA(n_components = 6)
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=6, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [8]:
# Autovalores
autoval = np.round(pca.explained_variance_, 1)
print('Autovalores')
print(autoval)

Autovalores
[194.7  67.1   0.    0.    0.    0. ]


In [9]:
# Autovetores
autovet = pca.components_
print('Autovetores')
print(autovet)

Autovetores
[[-0.75343787 -0.3217999  -0.0128598  -0.0560527  -0.15790534 -0.54821057]
 [ 0.63532027 -0.51724365 -0.01366776 -0.08280469  0.02122683 -0.56686255]
 [-0.01238169  0.02792093 -0.83297165 -0.5468764   0.04752295  0.06239482]
 [ 0.15050344  0.69069588  0.0987777  -0.21279664 -0.49153953 -0.45126197]
 [ 0.03728243  0.16530183 -0.53622068  0.79877911 -0.01402504 -0.2133259 ]
 [ 0.06711893 -0.3517652  -0.09228431  0.08716195 -0.85472164  0.35368575]]


In [10]:
# Variância explicada
var_exp = pca.explained_variance_ratio_ * 100
var_exp = np.round(var_exp, 2)
print('Variância explicada %:')
print(var_exp)

Variância explicada %:
[74.37 25.63  0.    0.    0.    0.  ]


In [11]:
# Variância explicada acumulada
var_exp_cum = np.cumsum(var_exp)
print('Variância explicada acumulada')
print(var_exp_cum)

Variância explicada acumulada
[ 74.37 100.   100.   100.   100.   100.  ]


In [12]:
# Carga Fatorial
AR = autovet * (autoval * 0.5)
print('Carga Fatorial:')
print(np.round(AR, 2))

Carga Fatorial:
[[-73.35 -10.8   -0.    -0.    -0.    -0.  ]
 [ 61.85 -17.35  -0.    -0.     0.    -0.  ]
 [ -1.21   0.94  -0.    -0.     0.     0.  ]
 [ 14.65  23.17   0.    -0.    -0.    -0.  ]
 [  3.63   5.55  -0.     0.    -0.    -0.  ]
 [  6.53 -11.8   -0.     0.    -0.     0.  ]]


In [13]:
# Tabela com os resultados
cp = ['PC %s' %i for i in range(1, len(autoval)+1)]
df = pd.DataFrame({'autovalores': autoval,
                      'var_exp_cum': var_exp_cum,
                      'var_exp': var_exp,
                      'Componente': cp})
df

autovalores  var_exp_cum  var_exp Componente
0        194.7        74.37    74.37       PC 1
1         67.1       100.00    25.63       PC 2
2          0.0       100.00     0.00       PC 3
3          0.0       100.00     0.00       PC 4
4          0.0       100.00     0.00       PC 5
5          0.0       100.00     0.00       PC 6

**2. O arquivo HypoGyre.mat consiste em uma serie temporal de dados artificiais de altura do nível do mar organizados na forma de mapas tridimensionais (Lon, Lat, tempo). Converta os dados na forma adequada para o calculo das EOFs, plote as principais EOFs assim como a sua variação temporal. Interprete o resultado obtido da forma que julgar conveniente.**

In [14]:
# Carregando os dados
data = loadmat('HypoGyre.mat')

In [15]:
# Identificando o tipo de cada chave no dicionario
for key in data.keys():
    print(key, '\t', data[key])

__header__ 	 b'MATLAB 5.0 MAT-file, Platform: PCWIN, Created on: Thu Jul 24 22:12:54 2008'
__version__ 	 1.0
__globals__ 	 []
x 	 [[-1.57079633 -1.46246555 -1.35413476 -1.24580398 -1.1374732  -1.02914242
  -0.92081164 -0.81248086 -0.70415008 -0.5958193  -0.48748852 -0.37915773
  -0.27082695 -0.16249617 -0.05416539  0.05416539  0.16249617  0.27082695
   0.37915773  0.48748852  0.5958193   0.70415008  0.81248086  0.92081164
   1.02914242  1.1374732   1.24580398  1.35413476  1.46246555  1.57079633]]
y 	 [[-1.57079633 -1.46246555 -1.35413476 -1.24580398 -1.1374732  -1.02914242
  -0.92081164 -0.81248086 -0.70415008 -0.5958193  -0.48748852 -0.37915773
  -0.27082695 -0.16249617 -0.05416539  0.05416539  0.16249617  0.27082695
   0.37915773  0.48748852  0.5958193   0.70415008  0.81248086  0.92081164
   1.02914242  1.1374732   1.24580398  1.35413476  1.46246555  1.57079633]]
t 	 [[-3.01069296 -2.74889357 -2.48709418 -2.2252948  -1.96349541 -1.70169602
  -1.43989663 -1.17809725 -0.91629786 -0.654

In [16]:
# Acessando os dados
lon = data.get('x') 
lat = data.get('y') 
time = data.get('t') 
ssh = data.get('Z') 

In [17]:
# Dimensões dos dados
print('Latitude')
print(lat.shape)
print('-='*15)
print('Longitude')
print(lon.shape)
print('-='*15)
print('Tempo')
print(time.shape)
print('-='*15)
print('SSH')
print(ssh.shape)

Latitude
(1, 30)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Longitude
(1, 30)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Tempo
(1, 24)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
SSH
(30, 30, 24)


In [18]:
# Criando a matriz N (tempo) x M (espaço) [24x900]
dados = ssh.ravel() # [21000,1]
dados = dados.reshape(900,24) # [900,24]
dados = dados.T
dados.shape

(24, 900)

In [19]:
# Criando DataFrame dos dados
z = pd.DataFrame(dados)
z.head()

0            1            2            3            4    \
0  7945.275845  7946.165745  7946.219127  7945.977255  7946.035579   
1  6722.561673  6723.451573  6723.504955  6723.263083  6723.321407   
2  2159.330260  2160.220159  2160.273542  2160.031669  2160.089994   
3 -1181.186982 -1180.297082 -1180.243700 -1180.485572 -1180.427248   
4    41.527190    42.417090    42.470472    42.228600    42.286924   

           5            6            7            8            9    ...  \
0  7945.501344  7945.344492  7945.296945  7945.764571  7946.021530  ...   
1  6722.787172  6722.630320  6722.582773  6723.050399  6723.307358  ...   
2  2159.555759  2159.398907  2159.351359  2159.818985  2160.075945  ...   
3 -1180.961483 -1181.118335 -1181.165882 -1180.698256 -1180.441297  ...   
4    41.752689    41.595837    41.548290    42.015916    42.272875  ...   

           890          891          892          893          894  \
0  7946.168010  7945.927135  7945.841138  7945.660153  7946.206020   
1  6723.453838  6723.212963  6723.126966  6722.945981  6723.491848   
2  2160.222425  2159.981549  2159.895552  2159.714567  2160.260434   
3 -1180.294817 -1180.535692 -1180.621689 -1180.802674 -1180.256807   
4    42.419355    42.178480    42.092483    41.911498    42.457365   

           895          896          897          898          899  
0  7946.011059  7945.918693  7945.282363  7945.840465  7945.313018  
1  6723.296887  6723.204521  6722.568191  6723.126293  6722.598846  
2  2160.065474  2159.973108  2159.336777  2159.894880  2159.367433  
3 -1180.451768 -1180.544134 -1181.180464 -1180.622362 -1181.149809  
4    42.262404    42.170038    41.533708    42.091810    41.564363  

[5 rows x 900 columns]

In [20]:
# Matriz covariância
dados_t = dados.T
ssh_cov = np.cov(dados_t)
print('Matriz covariância:')
print(ssh_cov)

Matriz covariância:
[[11644231.76342863 11644231.76342863 11644231.76342863 ...
  11644231.76342863 11644231.76342863 11644231.76342863]
 [11644231.76342863 11644231.76342863 11644231.76342863 ...
  11644231.76342863 11644231.76342863 11644231.76342863]
 [11644231.76342863 11644231.76342863 11644231.76342863 ...
  11644231.76342863 11644231.76342863 11644231.76342863]
 ...
 [11644231.76342863 11644231.76342863 11644231.76342863 ...
  11644231.76342863 11644231.76342863 11644231.76342863]
 [11644231.76342863 11644231.76342863 11644231.76342863 ...
  11644231.76342863 11644231.76342863 11644231.76342863]
 [11644231.76342863 11644231.76342863 11644231.76342863 ...
  11644231.76342863 11644231.76342863 11644231.76342863]]


In [21]:
# Autovalores e  autovetores
auto_val, auto_vec = np.linalg.eig(ssh_cov)
idx = auto_val.argsort()[::-1]
auto_val = auto_val[idx]
auto_vec = auto_vec[:,idx]

In [22]:
# Autovalores
print('Autovalores')
print(np.round(auto_val,2))

Autovalores
[ 1.04798153e+10+0.j  4.26109000e+03+0.j  0.00000000e+00+0.j
  0.00000000e+00+0.j  0.00000000e+00-0.j  0.00000000e+00+0.j
  0.00000000e+00+0.j  0.00000000e+00+0.j  0.00000000e+00-0.j
  0.00000000e+00+0.j  0.00000000e+00-0.j  0.00000000e+00+0.j
  0.00000000e+00-0.j  0.00000000e+00+0.j  0.00000000e+00+0.j
  0.00000000e+00-0.j  0.00000000e+00+0.j  0.00000000e+00-0.j
  0.00000000e+00+0.j  0.00000000e+00-0.j  0.00000000e+00+0.j
  0.00000000e+00-0.j  0.00000000e+00+0.j  0.00000000e+00-0.j
  0.00000000e+00+0.j  0.00000000e+00-0.j  0.00000000e+00+0.j
  0.00000000e+00-0.j  0.00000000e+00+0.j  0.00000000e+00-0.j
  0.00000000e+00+0.j  0.00000000e+00-0.j  0.00000000e+00+0.j
  0.00000000e+00-0.j  0.00000000e+00+0.j  0.00000000e+00+0.j
  0.00000000e+00-0.j  0.00000000e+00+0.j  0.00000000e+00-0.j
  0.00000000e+00+0.j  0.00000000e+00-0.j  0.00000000e+00+0.j
  0.00000000e+00-0.j  0.00000000e+00+0.j  0.00000000e+00-0.j
  0.00000000e+00+0.j  0.00000000e+00-0.j  0.00000000e+00+0.j
  0.00000000

In [23]:
# Autovetores
print('Autovetores')
print(np.round(auto_vec,2))

Autovetores
[[ 0.03+0.j   -0.04+0.j   -0.04+0.j   ...  0.01+0.01j  0.02-0.01j
   0.02+0.01j]
 [ 0.03+0.j   -0.04+0.j    0.06+0.j   ...  0.  +0.j    0.01-0.j
   0.01+0.j  ]
 [ 0.03+0.j   -0.04+0.j    0.07+0.j   ...  0.01+0.01j  0.02-0.j
   0.02+0.j  ]
 ...
 [ 0.03+0.j   -0.04+0.j    0.06+0.j   ...  0.01+0.01j  0.02-0.j
   0.02+0.j  ]
 [ 0.03+0.j   -0.04+0.j    0.07+0.j   ... -0.  +0.j    0.01-0.j
   0.01+0.j  ]
 [ 0.03+0.j   -0.04+0.j    0.06+0.j   ...  0.01+0.01j  0.02-0.j
   0.02+0.j  ]]


In [24]:
# Carga Fatorial
ar = auto_vec * (auto_val * 0.5)
print('Carga fatorial')
print(np.round(ar,2))

Carga fatorial
[[ 1.74663476e+08+0.j -8.91100000e+01+0.j -0.00000000e+00+0.j ...
  -0.00000000e+00-0.j -0.00000000e+00+0.j -0.00000000e+00-0.j]
 [ 1.74663476e+08+0.j -8.91100000e+01+0.j  0.00000000e+00+0.j ...
  -0.00000000e+00-0.j -0.00000000e+00+0.j -0.00000000e+00-0.j]
 [ 1.74663476e+08+0.j -8.91100000e+01+0.j  0.00000000e+00+0.j ...
  -0.00000000e+00-0.j -0.00000000e+00+0.j -0.00000000e+00-0.j]
 ...
 [ 1.74663476e+08+0.j -8.91100000e+01+0.j  0.00000000e+00+0.j ...
  -0.00000000e+00-0.j -0.00000000e+00+0.j -0.00000000e+00-0.j]
 [ 1.74663476e+08+0.j -8.91100000e+01+0.j  0.00000000e+00+0.j ...
   0.00000000e+00-0.j -0.00000000e+00+0.j -0.00000000e+00-0.j]
 [ 1.74663476e+08+0.j -8.91100000e+01+0.j  0.00000000e+00+0.j ...
  -0.00000000e+00-0.j -0.00000000e+00+0.j -0.00000000e+00-0.j]]
